name: Increment version tag

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  increment-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous version tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 'v1.0.0'
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: "echo"
        run: "echo 'new version ${{ steps.semvers.outputs.v_major }}'"
      - name: 'Push new semver tag'
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.semvers.outputs.v_major }}
