name: Increment version tag

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  increment-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous version tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 'v1.0.0'
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: "Log version"
        run: "echo 'New version is: ${{ steps.semvers.outputs.v_minor }}'"
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.semvers.outputs.v_minor }}"
          message: "Release ${{ steps.semvers.outputs.v_minor }}"
